#------------------
# HEATMAPS
#------------------

load("vsd.RData")
load("pvals.RData")
source("uniHeatmap.R")
# loading annotations - two-column tables
gg=read.table("mcav_holobiont_iso2gene.tab",sep="\t", quote="", comment.char="")  # gene names
str(gg)
#gg=gg[-grep("Uncharacterized",gg)$V2,]
kogs=read.table("mcav_iso2kogClass.tab",sep="\t", quote="", comment.char="")  # KOG classes
str(kogs)

design$time.depth=paste(design$time,design$depth,sep=".")
design$time.depth<-factor(design$time.depth, levels=c("zero.mesophotic","zero.shallow","zero.transplant","six.mesophotic","six.shallow","six.transplant","twelve.mesophotic","twelve.shallow","twelve.transplant"))
design[order(design$time.depth),]

# reordering columns according to time, then depth
head(vsd)
vsd.time=vsd[,order(design$time.depth)]
head(vsd.time)

design$time.depth<-factor(design$time.depth, levels=c("zero.mesophotic","six.mesophotic","twelve.mesophotic","zero.shallow","six.shallow","twelve.shallow","zero.transplant","six.transplant","twelve.transplant"))
design[order(design$time.depth),]

# reordering columns according to site, then depth
vsd.depth=vsd[,order(design$time.depth)]
head(vsd.depth)

#--------------

# loading WGCNA module kMEs 
upStress=read.csv("turquoise.csv")
downStress=read.csv("blue.csv")

#--------------
# all genes passing a cutoff, for treatment
# use for identifying large patterns, like genotypic differences
# install.packages("pheatmap")
library(pheatmap)

#--------------
# time pvals

pdf(file="heatmap_time_timedepth.pdf", height=20, width=15)
uniHeatmap(vsd=vsd.time,gene.names=gg,
	metric=time$pvalue, # metric of gene significance
	cutoff=0.01, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_time_depthtime.pdf", height=15, width=35)
uniHeatmap(vsd= vsd.depth,gene.names=gg,
	metric= time$pvalue, # metric of gene significance
	cutoff= 0.01, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

#--------------
# depth pvals

pdf(file="heatmap_depth_timedepth.pdf", height=15, width=35)
uniHeatmap(vsd=vsd.time,gene.names=gg,
	metric=depth$pvalue, # metric of gene significance
	cutoff= 0.05, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_depth_depthtime.pdf", height=15, width=35)
uniHeatmap(vsd= vsd.depth,gene.names=gg,
	metric= depth$pvalue, # metric of gene significance
	cutoff= 0.05, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

#------------------------------
# by pattern in gene name 

pattern="ribosom"

# how many genes we have with this pattern in gene name? 
sum(gg[grep(pattern,gg$V2),1] %in% row.names(vsd)) 

# plotting the ones that pass 0.1 pvalue cutoff:
pdf(file="heatmap_depth_ribosom.pdf", height=10, width=35)
nums=uniHeatmap(vsd=vsd.time,gene.names=gg,
	metric=depth$pvalue, # metric of gene significance
	cutoff=0.1, 
	sort=c(1:ncol(vsd)),  # overrides sorting of columns according to hierarchical clustering
	pattern=pattern,  # pattern in gene name
	cex=0.9,  # font size
	pdf=FALSE   # change to TRUE to print to PDF
	)
dev.off()
nums # totalCutoffPassing, named, patternMatching 

# plotting the ones that pass 0.01 pvalue cutoff:
pdf(file="heatmap_time_ribo.pdf", height=15, width=35)
nums=uniHeatmap(vsd=vsd.time,gene.names=gg,
	metric=time$pvalue, # metric of gene significance
	cutoff=0.01, 
	sort=c(1:ncol(vsd)),  # overrides sorting of columns according to hierarchical clustering
	pattern=pattern,  # pattern in gene name
	cex=0.9,  # font size
	pdf=FALSE   # change to TRUE to print to PDF
	)
dev.off()
nums # totalCutoffPassing, named, patternMatching 

#----------------
# top 5 percent significant genes (annotated only)

cutoff=0.1
metric=site$pvalue
top5percent=ceiling(table(metric<0.05)[2]*cutoff)
tops=row.names(head(site[order(metric),],top5percent))
nums=uniHeatmap(vsd=vsd.site[tops,],gene.names=gg,
	metric= site[tops,]$pvalue,
	cutoff=cutoff,
	sort=c(1:ncol(vsd.site)),  
	cex=0.8,
	pdf=FALSE
	)
nums # totalCutoffPassing, named, patternMatching 
#-------------------
# by pattern in KOG class name

kog.pattern="metabolic"

isos=as.character(kogs$V1[grep(kog.pattern,kogs$V2)])
sevsd=vsd[row.names(vsd) %in% isos,]
sel.depth =depth[row.names(depth) %in% isos,]

nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.depth$pvalue,
	cutoff=0.01,
	sort=c(1:ncol(vsd)),  
	cex=0.8,
	pdf=FALSE
	)

#--------------------
# loading GO annotations - lists of genes for each GO term (plus some additional info) - these files are generated by GOMWU.R script
# full model, overall factors
gos.lpv.mf=read.table("MF_site_lpv.csv",sep="\t",header=T)
gos.lpv.bp=read.table("BP_site_lpv.csv",sep="\t",header=T)
gos.lpv.cc=read.table("CC_site_lpv.csv",sep="\t",header=T)

god.fc.mf=read.table("MF_depth_fc.csv",sep="\t",header=T)
god.fc.bp=read.table("BP_depth_fc.csv",sep="\t",header=T)
god.fc.cc=read.table("CC_depth_fc.csv",sep="\t",header=T)

god.lpv.mf=read.table("MF_depth_lpv.csv",sep="\t",header=T)
god.lpv.cc=read.table("CC_depth_lpv.csv",sep="\t",header=T)
god.lpv.bp=read.table("BP_depth_lpv.csv",sep="\t",header=T)

goi.fc.mf=read.table("MF_int_fc.csv",sep="\t",header=T)
goi.fc.bp=read.table("BP_int_fc.csv",sep="\t",header=T)
goi.fc.cc=read.table("CC_int_fc.csv",sep="\t",header=T)

goi.lpv.mf=read.table("MF_int_lpv.csv",sep="\t",header=T)
goi.lpv.cc=read.table("CC_int_lpv.csv",sep="\t",header=T)
goi.lpv.bp=read.table("BP_int_lpv.csv",sep="\t",header=T)

#--------------
# depth differences across sites

goCBC.fc.mf=read.table("MF_CBC_fc.csv",sep="\t",header=T)
goCBC.fc.bp=read.table("BP_CBC_fc.csv",sep="\t",header=T)
goCBC.fc.cc=read.table("CC_CBC_fc.csv",sep="\t",header=T)

goCBC.lpv.mf=read.table("MF_CBC_lpv.csv",sep="\t",header=T)
goCBC.lpv.cc=read.table("CC_CBC_lpv.csv",sep="\t",header=T)
goCBC.lpv.bp=read.table("BP_CBC_lpv.csv",sep="\t",header=T)

goWFGB.fc.mf=read.table("MF_WFGB_fc.csv",sep="\t",header=T)
goWFGB.fc.bp=read.table("BP_WFGB_fc.csv",sep="\t",header=T)
goWFGB.fc.cc=read.table("CC_WFGB_fc.csv",sep="\t",header=T)

goWFGB.lpv.mf=read.table("MF_WFGB_lpv.csv",sep="\t",header=T)
goWFGB.lpv.cc=read.table("CC_WFGB_lpv.csv",sep="\t",header=T)
goWFGB.lpv.bp=read.table("BP_WFGB_lpv.csv",sep="\t",header=T)

goEFGB.fc.mf=read.table("MF_EFGB_fc.csv",sep="\t",header=T)
goEFGB.fc.bp=read.table("BP_EFGB_fc.csv",sep="\t",header=T)
goEFGB.fc.cc=read.table("CC_EFGB_fc.csv",sep="\t",header=T)

goEFGB.lpv.mf=read.table("MF_EFGB_lpv.csv",sep="\t",header=T)
goEFGB.lpv.cc=read.table("CC_EFGB_lpv.csv",sep="\t",header=T)
goEFGB.lpv.bp=read.table("BP_EFGB_lpv.csv",sep="\t",header=T)

goPRTER.fc.mf=read.table("MF_PRTER_fc.csv",sep="\t",header=T)
goPRTER.fc.bp=read.table("BP_PRTER_fc.csv",sep="\t",header=T)
goPRTER.fc.cc=read.table("CC_PRTER_fc.csv",sep="\t",header=T)

goPRTER.lpv.mf=read.table("MF_PRTER_lpv.csv",sep="\t",header=T)
goPRTER.lpv.cc=read.table("CC_PRTER_lpv.csv",sep="\t",header=T)
goPRTER.lpv.bp=read.table("BP_PRTER_lpv.csv",sep="\t",header=T)

#--------------------
# by pattern in GO term

go.pattern="sensory perception"

goDiv=gos.bp 
# if you want mf or bp, need to change this above 
goDiv[grep(go.pattern,goDiv$name),]
isos=as.character(goDiv$seq[grep(go.pattern,goDiv$name)])
sevsd=vsd[row.names(vsd) %in% isos,]
sel.trt=trt[row.names(trt) %in% isos,]

nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.trt$pvalue,
	cutoff=0.01,
	sort=c(1:ncol(vsd)),  
	cex=0.8,
	pdf=FALSE
	)

#---------------------
# by WGCNA module membership (sorted from high to low)

module=upStress
cutoff=0.85 # module membership cutoff
signed=T

if (signed) { 
	inModule=module[abs(module[,2])>cutoff,] 
	} else {
		 inModule=module[module[,2]>cutoff,]
	}
genes=inModule[order(inModule[,2],decreasing=T),1]
genes=genes[genes %in% row.names(vsd)]
nums=uniHeatmap(vsd[genes,],gene.names=gg,
	metric=depth[genes,]$pvalue,
	cutoff=1,
	cluster_rows=F,
	sort=c(1:ncol(vsd)),  
	cex=0.8,	
	pdf=FALSE
	)
nums # totalCutoffPassing, named, patternMatching 

#------------------------------
# comparing expression of conserved DEGs across site
library(pheatmap)
source("uniHeatmap.R")

common=read.csv("commongenes_vsd.csv", head=TRUE, row.names=1)
class(common)

# reordering columns according to site, then depth
common.depth= common[,order(design$depth,design$site)]
head(common.depth)

# reordering columns according to site, then depth
common.site= common[,order(design$site,design$depth)]
head(common.site)

pdf(file="heatmap_common_sitedepth.pdf", height=35, width=35)
uniHeatmap(vsd= common.site,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=1, 
	sort=c(1:ncol(common.site)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_common_depthsite.pdf", height=35, width=35)
uniHeatmap(vsd= common.depth,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=1, 
	sort=c(1:ncol(common.depth)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()