#------------------
# HEATMAPS
#------------------

load("vsd.RData")
load("pvals.RData")
source("uniHeatmap.R")
# loading annotations - two-column tables
gg=read.table("Mcavernosa_Cladocopium_iso2geneName.tab",sep="\t", quote="", comment.char="")  # gene names
str(gg)
#gg=gg[-grep("Uncharacterized",gg)$V2,]
kogs=read.table("Mcavernosa_Cladocopium_iso2kogClass.tab",sep="\t", quote="", comment.char="")  # KOG classes
str(kogs)

design$site.depth=paste(design$site,design$depth,sep=".")
design$site.depth<-factor(design$site.depth, levels=c("BLZ.mesophotic","WFGB.mesophotic","EFGB.mesophotic","PRG-DRT.mesophotic","BLZ.shallow","WFGB.shallow","EFGB.shallow","PRG-DRT.shallow"))
design[order(design$site.depth),]

# reordering columns according to depth, then site
head(vsd)
#vsd.depth=vsd[,order(design$depth,design$site)]
vsd.depth=vsd[,order(design$site.depth)]
head(vsd.depth)

design$site.depth<-factor(design$site.depth, levels=c("BLZ.mesophotic","BLZ.shallow","WFGB.mesophotic","WFGB.shallow","EFGB.mesophotic","EFGB.shallow","PRG-DRT.mesophotic","PRG-DRT.shallow"))
design[order(design$site.depth),]

# reordering columns according to site, then depth
#vsd.site=vsd[,order(design$site,design$depth)]
vsd.site=vsd[,order(design$site.depth)]

#--------------

# loading WGCNA module kMEs 
# upStress=read.csv("../WGCNA/blue_inModMWU.csv")
# downStress=read.csv("../WGCNA/lightgreen_inModMWU.csv")

#--------------
# all genes passing a cutoff, for treatment
# use for identifying large patterns, like genotypic differences
# install.packages("pheatmap")
library(pheatmap)

#--------------
# site pvals

pdf(file="heatmap_site_depthsite.pdf", height=10, width=50)
uniHeatmap(vsd=vsd.depth,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=1E-8, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_site_sitedepth.pdf", height=10, width=50)
uniHeatmap(vsd= vsd.site,gene.names=gg,
	metric= site$pvalue, # metric of gene significance
	cutoff=1E-8, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

#--------------
# depth pvals

pdf(file="heatmap_depth_depthsite.pdf", height=10, width=40)
uniHeatmap(vsd=vsd.depth,gene.names=gg,
	metric=depth$pvalue, # metric of gene significance
	cutoff=0.001, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_depth_sitedepth.pdf", height=10, width=40)
uniHeatmap(vsd= vsd.site,gene.names=gg,
	metric=depth$pvalue, # metric of gene significance
	cutoff=0.001, 
	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

#------------------------------
# by pattern in gene name 

pattern="ribo"

# how many genes we have with this pattern in gene name? 
sum(gg[grep(pattern,gg$V2),1] %in% row.names(vsd)) 

# plotting the ones that pass 0.1 pvalue cutoff:
pdf(file="heatmap_depth_ribo.pdf", height=10, width=35)
nums=uniHeatmap(vsd=vsd.site,gene.names=gg,
	metric=depth$pvalue, # metric of gene significance
	cutoff=0.1, 
	sort=c(1:ncol(vsd)),  # overrides sorting of columns according to hierarchical clustering
	pattern=pattern,  # pattern in gene name
	cex=0.9,  # font size
	pdf=FALSE   # change to TRUE to print to PDF
	)
dev.off()
nums # totalCutoffPassing, named, patternMatching 

# plotting the ones that pass 0.01 pvalue cutoff:
pdf(file="heatmap_site_ribo.pdf", height=15, width=35)
nums=uniHeatmap(vsd=vsd.site,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=0.01, 
	sort=c(1:ncol(vsd)),  # overrides sorting of columns according to hierarchical clustering
	pattern=pattern,  # pattern in gene name
	cex=0.9,  # font size
	pdf=FALSE   # change to TRUE to print to PDF
	)
dev.off()
nums # totalCutoffPassing, named, patternMatching 

#----------------
# top 5 percent significant genes (annotated only)

cutoff=0.1
metric=site$pvalue
top5percent=ceiling(table(metric<0.05)[2]*cutoff)
tops=row.names(head(site[order(metric),],top5percent))
pdf(file="heatmap_topsig.pdf", height=15, width=35)
uniHeatmap(vsd=vsd.site[tops,],gene.names=gg,
	metric= site[tops,]$pvalue,
	cutoff=cutoff,
	sort=c(1:ncol(vsd.site)),  
	cex=0.8,
	pdf=FALSE
	)
dev.off()
 # totalCutoffPassing, named, patternMatching 
#-------------------
# by pattern in KOG class name

kog.pattern="metabolic"

isos=as.character(kogs$V1[grep(kog.pattern,kogs$V2)])
sevsd=vsd[row.names(vsd) %in% isos,]
sel.depth =depth[row.names(depth) %in% isos,]

nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.depth$pvalue,
	cutoff=0.01,
	sort=c(1:ncol(vsd)),  
	cex=0.8,
	pdf=FALSE
	)

#--------------------
# loading GO annotations - lists of genes for each GO term (plus some additional info) - these files are generated by GOMWU.R script
# full model, overall factors
gos.lpv.mf=read.table("MF_site_lpv.csv",sep="\t",header=T)
gos.lpv.bp=read.table("BP_site_lpv.csv",sep="\t",header=T)
gos.lpv.cc=read.table("CC_site_lpv.csv",sep="\t",header=T)

god.fc.mf=read.table("MF_depth_fc.csv",sep="\t",header=T)
god.fc.bp=read.table("BP_depth_fc.csv",sep="\t",header=T)
god.fc.cc=read.table("CC_depth_fc.csv",sep="\t",header=T)

god.lpv.mf=read.table("MF_depth_lpv.csv",sep="\t",header=T)
god.lpv.cc=read.table("CC_depth_lpv.csv",sep="\t",header=T)
god.lpv.bp=read.table("BP_depth_lpv.csv",sep="\t",header=T)

goi.fc.mf=read.table("MF_int_fc.csv",sep="\t",header=T)
goi.fc.bp=read.table("BP_int_fc.csv",sep="\t",header=T)
goi.fc.cc=read.table("CC_int_fc.csv",sep="\t",header=T)

goi.lpv.mf=read.table("MF_int_lpv.csv",sep="\t",header=T)
goi.lpv.cc=read.table("CC_int_lpv.csv",sep="\t",header=T)
goi.lpv.bp=read.table("BP_int_lpv.csv",sep="\t",header=T)

#--------------
# depth differences across sites

goBLZ.fc.mf=read.table("MF_BLZ_fc.csv",sep="\t",header=T)
goBLZ.fc.bp=read.table("BP_BLZ_fc.csv",sep="\t",header=T)
goBLZ.fc.cc=read.table("CC_BLZ_fc.csv",sep="\t",header=T)

goBLZ.lpv.mf=read.table("MF_BLZ_lpv.csv",sep="\t",header=T)
goBLZ.lpv.cc=read.table("CC_BLZ_lpv.csv",sep="\t",header=T)
goBLZ.lpv.bp=read.table("BP_BLZ_lpv.csv",sep="\t",header=T)

goWFGB.fc.mf=read.table("MF_WFGB_fc.csv",sep="\t",header=T)
goWFGB.fc.bp=read.table("BP_WFGB_fc.csv",sep="\t",header=T)
goWFGB.fc.cc=read.table("CC_WFGB_fc.csv",sep="\t",header=T)

goWFGB.lpv.mf=read.table("MF_WFGB_lpv.csv",sep="\t",header=T)
goWFGB.lpv.cc=read.table("CC_WFGB_lpv.csv",sep="\t",header=T)
goWFGB.lpv.bp=read.table("BP_WFGB_lpv.csv",sep="\t",header=T)

goEFGB.fc.mf=read.table("MF_EFGB_fc.csv",sep="\t",header=T)
goEFGB.fc.bp=read.table("BP_EFGB_fc.csv",sep="\t",header=T)
goEFGB.fc.cc=read.table("CC_EFGB_fc.csv",sep="\t",header=T)

goEFGB.lpv.mf=read.table("MF_EFGB_lpv.csv",sep="\t",header=T)
goEFGB.lpv.cc=read.table("CC_EFGB_lpv.csv",sep="\t",header=T)
goEFGB.lpv.bp=read.table("BP_EFGB_lpv.csv",sep="\t",header=T)

goPRG-DRT.fc.mf=read.table("MF_PRG-DRT_fc.csv",sep="\t",header=T)
goPRG-DRT.fc.bp=read.table("BP_PRG-DRT_fc.csv",sep="\t",header=T)
goPRG-DRT.fc.cc=read.table("CC_PRG-DRT_fc.csv",sep="\t",header=T)

goPRG-DRT.lpv.mf=read.table("MF_PRG-DRT_lpv.csv",sep="\t",header=T)
goPRG-DRT.lpv.cc=read.table("CC_PRG-DRT_lpv.csv",sep="\t",header=T)
goPRG-DRT.lpv.bp=read.table("BP_PRG-DRT_lpv.csv",sep="\t",header=T)

#--------------------
# by pattern in GO term

go.pattern="sensory perception"

goDiv=gos.bp 
# if you want mf or bp, need to change this above 
goDiv[grep(go.pattern,goDiv$name),]
isos=as.character(goDiv$seq[grep(go.pattern,goDiv$name)])
sevsd=vsd[row.names(vsd) %in% isos,]
sel.trt=trt[row.names(trt) %in% isos,]

nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.trt$pvalue,
	cutoff=0.01,
	sort=c(1:ncol(vsd)),  
	cex=0.8,
	pdf=FALSE
	)

#---------------------
# by WGCNA module membership (sorted from high to low)

module=upStress
cutoff=0.85 # module membership cutoff
signed=T

if (signed) { 
	inModule=module[abs(module[,2])>cutoff,] 
	} else {
		 inModule=module[module[,2]>cutoff,]
	}
genes=inModule[order(inModule[,2],decreasing=T),1]
genes=genes[genes %in% row.names(vsd)]
nums=uniHeatmap(vsd[genes,],gene.names=gg,
	metric=trt[genes,]$pvalue,
	cutoff=1,
	cluster_rows=F,
	sort=c(1:ncol(vsd)),  
	cex=0.8,	
	pdf=FALSE
	)
nums # totalCutoffPassing, named, patternMatching 

#------------------------------
# comparing expression of conserved DEGs across site
library(pheatmap)
load("vsd.RData")
source("uniHeatmap.R")

common=read.csv("commongenes_vsd.csv", head=TRUE, row.names=1)
class(common)

# reordering columns according to site, then depth
design$site.depth=paste(design$site,design$depth,sep=".")
design$site.depth<-factor(design$site.depth, levels=c("BLZ.mesophotic","WFGB.mesophotic","EFGB.mesophotic","PRG-DRT.mesophotic","BLZ.shallow","WFGB.shallow","EFGB.shallow","PRG-DRT.shallow"))
design[order(design$site.depth),]

# reordering columns according to depth, then site
common.depth= common[,order(design$site.depth)]
head(common.depth)

design$site.depth<-factor(design$site.depth, levels=c("BLZ.mesophotic","BLZ.shallow","WFGB.mesophotic","WFGB.shallow","EFGB.mesophotic","EFGB.shallow","PRG-DRT.mesophotic","PRG-DRT.shallow"))
design[order(design$site.depth),]

# reordering columns according to site, then depth
common.site= common[,order(design$site.depth)]
head(common.site)

pdf(file="heatmap_common_sitedepth.pdf", height=35, width=35)
uniHeatmap(vsd= common.site,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=1, 
	sort=c(1:ncol(common.site)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()

pdf(file="heatmap_common_depthsite.pdf", height=35, width=35)
uniHeatmap(vsd= common.depth,gene.names=gg,
	metric=site$pvalue, # metric of gene significance
	cutoff=1, 
	sort=c(1:ncol(common.depth)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.8,
	pdf=F
	)
dev.off()